First version of README.md
ClickHouse/clickhouse-beam-connector pull request #3
Opened 2024-09-09 13:01 UTC by mzitnik

2024-09-09 13:18 UTC, mzitnik commented
This is the first version of README file

2024-09-09 17:23 UTC, BentsiLeviav requested changes

2024-09-09 17:23 UTC, BentsiLeviav commented on README.md
> +<img src="https://github.com/ClickHouse/clickhouse-js/blob/a332672bfb70d54dfd27ae1f8f5169a6ffeea780/.static/logo.svg" width="200px" align="center">
If we add CH's logo, could you please add Beam's as well?

2024-09-09 17:23 UTC, BentsiLeviav commented on README.md
> +A Full Maven example with pom.xml definition see: [here](https://github.com/ClickHouse/clickhouse-beam-connector/tree/main/example/mvn)
If possible, please move the URL from the word here to the word example.

2024-09-09 17:25 UTC, mzitnik commented on README.md
> +<img src="https://github.com/ClickHouse/clickhouse-js/blob/a332672bfb70d54dfd27ae1f8f5169a6ffeea780/.static/logo.svg" width="200px" align="center">
I think we need have a ClickHouse logo with Beam inside

2024-09-09 17:27 UTC, mzitnik commented on README.md
> +A Full Maven example with pom.xml definition see: [here](https://github.com/ClickHouse/clickhouse-beam-connector/tree/main/example/mvn)
@BentsiLeviav 
I will change to `mvn`  since we are going to have `gradle` in the future

2024-09-10 11:40 UTC, BentsiLeviav approved these changes

2024-09-10 11:42 UTC, merged